# Generated by Django 6.0.7 on 2026-07-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttable',
            name='is_parcel',
            field=models.BooleanField(default=False),
        ),
    ]
