# Generated by Django 6.0.7 on 2026-07-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_restauranttable_is_parcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantsettings',
            name='gstin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='printer_mac',
            field=models.CharField(blank=True, help_text='Bluetooth printer MAC address', max_length=255),
        ),
    ]
