# Generated by Django 6.0.7 on 2026-07-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_restaurantsettings_gstin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='upi_id',
            field=models.CharField(blank=True, default='merchant@upi', max_length=200),
        ),
    ]
