# Generated by Django 6.0.7 on 2026-07-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_restaurantsettings_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
